import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Button } from 'antd';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>See Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.btnContainer}>
        <Link href="/user" passHref><Button type="primary">See Your Data</Button></Link>
      </div>
    </div>
  )
}
